# skills_db.py

skills = [
    "python",
    "sql",
    "machine learning",
    "deep learning",
    "nlp",
    "tensorflow",
    "pytorch",
    "power bi",
    "tableau",
    "excel",
    "aws",
    "docker",
    "kubernetes",
    "data analysis",
    "pandas",
    "numpy",
    "scikit-learn",
    "statistics",
    "ML",
    "DL",
    "AI",
    "data visualization",
    "data engineering",
    "cloud computing",
    "big data",
    "data science",
    "matplotlib",
    "seaborn",
    "git",
    "linux",
    "communication",
    "teamwork",
    "problem-solving",
    "project management",
    "leadership",
    "time management",
    "adaptability",
    "critical thinking",
    "creativity",
    "collaboration",
    "presentation skills",
    "Django",
    "Flask",
    "REST APIs",
    "microservices",
    "spark",
    "hadoop",
    "scala",
    "java",
    "c++",
    "javascript",
    "react",
    "angular",
    "vue",
    "html",
    "css",
    "agile",
    "scrum",
    "kanban",
    "devops",
    "ci/cd",
    "github",
    "gitlab",
    "bitbucket",
    "jenkins",
    "ansible",
    "terraform",
    "azure",
    "gcp",
    "windows",
    "macos",
    "PowerShell"
]